### ISSUE TITLE
exception while generating reports

### ISSUE THREAD

**Issue by jancajthaml** [jancajthaml-openbank/health-check#12]
```
You are using pip version 8.1.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
./reports/all_s1_new_account_latencies_5000.json
accounts grap calculations took [ 548 ys 362 ns ]
loading of accounts latencies scenario metrics took [ 7 ms 81 ys ]
Traceback (most recent call last):
  File "generate_metrics_report.py", line 382, in <module>
    main()
  File "generate_metrics_report.py", line 360, in main
    graph.compute(data)
  File "generate_metrics_report.py", line 125, in compute
    self.total_created_accounts = sum(self.accounts[maximum_ts-1].values())
KeyError: 0
Exited with code 1
```

**Comment by jancajthaml** [comment]
```
new accounts grap calculations took [ 5 ms 359 ys ]
new accounts grap plotting increments took [ 9 s 661 ms ]
new accounts grap plotting growth took [ 3 s 645 ms ]
loading of new accounts latencies scenario metrics took [ 13 s 327 ms ]
get accounts grap calculations took [ 3 ms 144 ys ]
loading of get accounts latencies scenario metrics took [ 35 ms 996 ys ]
Traceback (most recent call last):
  File "generate_metrics_report.py", line 552, in <module>
    main()
  File "generate_metrics_report.py", line 530, in main
    graph.compute(data, resources)
  File "generate_metrics_report.py", line 83, in compute
    self.result[num_of_accounts] = max(top)
ValueError: max() arg is an empty sequence
Exited with code 1
```

**Comment by jancajthaml** [comment]
correlation between number of created transactions and create new transaction request latency
```
Traceback (most recent call last):
  File "./scripts/main.py", line 612, in main
    graph.compute(data)
  File "./scripts/main.py", line 135, in compute
    for ts, stacks in self.transfers.items():
AttributeError: 'TransactionCreationAndLatenciesGraph' object has no attribute 'transfers'
```

correlation between existing accounts and get account request latency
```
Traceback (most recent call last):
  File "./scripts/main.py", line 642, in main
    graph.compute(data)
  File "./scripts/main.py", line 48, in compute
    self.result[num_of_accounts] = max(metrics.get_subset("vault-rest", 'getAccountLatency').values())
ValueError: max() arg is an empty sequence
```
